version: '3.8'
services:
  xvcf-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LISTEN_PORT: 8085
        VNC_PORT: 5900
    user: admin
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
