version: '3.8'
services:
  xvcf-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LISTEN_PORT: 8085
        VNC_PORT: 5900
    ports:
      - "8085:8085"
      - "5900:5900"
    user: admin
    shm_size: '16gb'
    pid: 'host'
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
